### PR TITLE
Remove columns from status.md that have been replaced by automated audit

### PR DESCRIPTION
**Pull request by Jericho**
Remove the `Added to Cake Website`, `Uses cake-contrib logo` and the `Supports .Net Core` columns from the `Addins` and from the `Modules` sections. The information that was in these columns is now automatically tracked by the Cake.AddinDiscoverer tool and refreshed twice a day (at noon and midnight GMT). This information is now avilable in Audit.md

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@Jericho sorry, I missed this PR before I added a new addin to the list.  Would you be in a position to fix this up?  If not, I will take care of it.  Thanks again!

**Comment by Jericho** [comment]
ok I rebased my branch. It was alittle bit tricky but I think I got it right. The new addin I noticed was cake.homebrew right?

**Comment by gep13** [comment]
@Jericho yes, that is the addin that I added.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@Jericho your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
